### PR TITLE
Fixed streaming in case openAI returns chunk without new line

### PR DESCRIPTION
**Pull request by remorses**
If a chunk has no new line (streamed only part of a chunk) parsing will fail. This PR adds a buffer to handle this case

### CODE REVIEW

**Comment by rileytomasek** [comment]
Thanks for the PR @remorses. Are you able to consistently reproduce this issue? What happens without your changes?
I'm using this library in prod extensively and I don't (think) I have seen this.

**Comment by remorses** [comment]
This issue only happened in Vercel edge environment in rare cases, sometimes the API would return incomplete JSON

**Comment by rileytomasek** [comment]
Hmm, are you sure it isn't an issue with the Vercel Edge functions? I'm hesitant to add platform specific edged case handling to this library, especially give that the streaming implementation doesn't have any tests. If you can share more context the next time you see it, I'd consider merging this if it isn't a Vercel bug.

**Comment by remorses** [comment]
It’s not a Vercel bug, when doing http streaming you are not guaranteed to have a new line in every chunk, most implementations do flush on every new lines but not all of them

this is common practice in parsing http streams, here is an example:  https://github.com/Azure/fetch-event-source/blob/a0529492576e094374602f24d5e64b3a271b4576/src/parse.ts#L89

**Comment by rileytomasek** [comment]
Resolved in [v1.6.5](https://github.com/dexaai/openai-fetch/releases/tag/v1.6.5)

**Pull request closed without merging**
