### PR TITLE
Add function calling support to chat completions

### PR DESCRIPTION
**Pull request by rileytomasek**
This continues from #26 

Adds support for function calling:
- [Announcement](https://openai.com/blog/function-calling-and-other-api-updates)
- [Guide](https://platform.openai.com/docs/guides/gpt/function-calling)
- [API Reference](https://platform.openai.com/docs/api-reference/chat/create)

**Todo:**
- [ ] Test/add streaming support

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
@rileytomasek What would you think about merging and releasing as-is via a minor version bump?

I know it's technically a breaking change, so we'd ideally want to combine this with the streaming support, but I think it's more important to get it released.

**Comment by rileytomasek** [comment]
> @rileytomasek What would you think about merging and releasing as-is via a minor version bump?
> 
> I know it's technically a breaking change, so we'd ideally want to combine this with the streaming support, but I think it's more important to get it released.

I'm fine with that. I *think* it would only be a breaking change at the types level, if at all.

**Comment by transitive-bullshit** [comment]
LGTM 👍

**Comment by rileytomasek** [comment]
Released as [v1.6.0](https://github.com/rileytomasek/openai-fetch/releases/tag/v1.6.0)

**Comment by transitive-bullshit** [comment]
I'm getting some undesired type errors after the latest updates:

CleanShot 2023-06-14 at 22 17 28@2x

```ts
// this gives a type error
if (completion.message.function_call) { ... }
```

```ts
// this works fine
if (completion.message.role === 'assistant' && completion.message.completion.message.function_call) { ... }
```

@rileytomasek I think both of these should work type-wise.

---

Another unrelated error where I'm less sure what's going on is that it seems like using an array of `messages` and appending a message result from a previous chat completion call results in a TS error when trying to pass that new messages array.

CleanShot 2023-06-14 at 22 20 09@2x

CleanShot 2023-06-14 at 22 22 44@2x

**Pull request merged**
