### PR TITLE
Update ChatMessage type with 'refusal' and 'content' is now optional

### PR DESCRIPTION
**Pull request by transitive-bullshit**
This change matches the updated types on OpenAI's side, which unfortunately means that `ChatMessage.content` is now no longer guaranteed to exist for `assistant` messages (if the model refused to generate the message).

### CODE REVIEW

**Review by rileytomasek — APPROVED** [review]
ugh, this is oh so annoying, but probably required. do you think we should have a special instance for this case and try to dynamically apply it when the structured output flag is enabled? or is this something that can actually apply to all cases now?

i guess we could also go the other way and keep this, and narrow the type when not in annoying mode :p

**Comment by transitive-bullshit** [comment]
yeah, I'm not sure the best way to handle it. imho `openai-fetch` should mirror the official types as closely as possible and not try to do anything too smart. that logic will come in dexter.

i've already made the switch for agentic, and it's actually not too bad; just annoying.

**Comment by rileytomasek** [comment]
That's fair. Let's keep this to spec and make it nicer to deal with in Dexter.

**Comment by transitive-bullshit** [comment]
@rileytomasek would you prefer this to be a minor or major bump version bump?

**Comment by rileytomasek** [comment]
> @rileytomasek would you prefer this to be a minor or major bump version bump?

oh good catch. probably a major to be safe. it's not like were doing marketing around each major version bump 😂.

**Pull request merged**
